name: Pipeline For Security And Style Check

on: [pull_request, push]

jobs:
  git-leaks:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Fetch all history for all tags and branches
        
        - name: Git Leaks Check
          uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Code Style
        run:  cd server/ && npm install && npm run lint:fix

  editor-config-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Editor Config Checker Action  
        uses: editorconfig-checker/action-editorconfig-checker@main
    
      - name: Run Editor Config Checker
        run:  editorconfig-checker

  markdown-files-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16' # run on 16 as version 12 is deprecated
        
      - name: Install Markdown Lint And Check Markdown Files
        run:  npm install -g markdownlint-cli && markdownlint '**/*.md'
  
  snyk-check:
    needs: [code-check, editor-config-check, markdown-files-check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Snyk
        uses: snyk/actions/setup@master
      
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'

      - name: Snyk monitor
        run: cd server/ && snyk auth ${{ secrets.SNYK_TOKEN }} && snyk test --severity-threshold=high
  
  sonarcloud:
    needs: [code-check, editor-config-check, markdown-files-check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          projectBaseDir: /github/workspace/server
          args: >
              -Dsonar.organization=${{ secrets.SONARCLOUD_ORG_TOKEN }}
              -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECT_KEY }}
              -Dsonar.tests=unit-tests/
              -Dsonar.verbose=true
  
  build-image:
    needs: [snyk-check, sonarcloud]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'

      - name: Navigate To Package.json file And Execute NPM install
        run: cd server/ && npm install

      - name: Build & Run Unit Tests
        run: cd server/ && tsc && npx jest

      - name: Login in DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git Commit SHA
        id: git_sha
        run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Tag Docker image
        run: cd server/ && docker build -t ${{ secrets.DOCKER_USERNAME }}/car-dealership-image:${{ env.SHA }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/car-dealership-image:${{ env.SHA }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/car-dealership-image:${{ env.SHA }}
