name: Pipeline For Security And Style Check

on: [pull_request, push]

jobs:
  git-leaks:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Fetch all history for all tags and branches
        
        - name: Git Leaks Check
          uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Code Style
        run:  cd server/ && npm install && npm run lint:fix

  editor-config-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Editor Config Checker Action  
        uses: editorconfig-checker/action-editorconfig-checker@main
    
      - name: Run Editor Config Checker
        run:  editorconfig-checker

  markdown-files-check:
    needs: git-leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16' # run on 16 as version 12 is deprecated
        
      - name: Install Markdown Lint And Check Markdown Files
        run:  npm install -g markdownlint-cli && markdownlint '**/*.md'
  
  snyk-check:
    needs: [code-check, editor-config-check, markdown-files-check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Snyk
        uses: snyk/actions/setup@master
      
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'

      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
